credentials:
  usernames:
    admin:
      name: Admin User
      password: $2b$12$/VzQBsaYWfkuiy256huAGOIxSqMqXwcE6565TsgZ1cDwaT9jsfZya
      role: admin
    editor:
      name: HR Editor
      password: $2b$12$cHs4llwXj6VxLvUax2VPlOuYiyW0NKDcjceq.hhKC3LJF1a5tMX/6
      role: editor
    viewer:
      name: HR Viewer
      password: $2b$12$cZi3uLwcFeEU4mKh91gbC.65269HfsGHVXkmVzvVLqRHrsItgy1p6
      role: viewer

cookie:
  name: hr_dashboard_cookie
  key: hr_analytics_secret_key_2024
  expiry_days: 30
